### ISSUE TITLE
Interactive plots and diagrams

### ISSUE THREAD

**Issue by mikepurvis** [ternaris/marv#13]
I'd like to be able to render interactive plots, in particular using bokeh and dygraphs, which are friendly to larger amounts of data. Would it make sense to add new widget types specific to these, or more of a generic "blob of HTML" widget into which could be stuffed this kinds of content?

Note that I'm also interested in generating multiple plots which are synchronized together, see: http://dygraphs.com/gallery/#g/synchronize

Finally, I'd like to be able to generate timelines of key events that are occurring during my bags. For example, marking out spans of time that the robot is parked vs. moving, faulted vs OK, charging vs. discharging, etc. For this, I'm interested in using vis.js, eg: http://visjs.org/timeline_examples.html

What's the best path forward on integrating these tools with MARV?

**Comment by NikolausDemmel** [comment]
There is some support for interactive plots using [mpld3](http://mpld3.github.io/), which is a really convenient way to bring your matplotlib plots to the browser, but I have also found that they don't scale increadibly well with large amounts of data and when playing around with a while back I couldn't make all plugins work right away.

I believe it would make sense to support other js plotting libraries explicitly as plugins, but a generic "blob of HTML" would also be great in particular for the adventurous user like yourself that doesn't mind digging in the plumbing to get the desired result. However, @chaoflow will have to way in as I have no idea what the plans are here.

**Comment by luator** [comment]
I am interested in this as well. Is there some documentation or example on how to use mpld3? I saw in the demo that it is used there but could not yet figure out how to do so (what type of detail widget do I need?).

**Comment by NikolausDemmel** [comment]
> I am interested in this as well. Is there some documentation or example on how to use mpld3? I saw in the demo that it is used there but could not yet figure out how to do so (what type of detail widget do I need?).

To be honest, I'm not even sure that the mpld3 widgets are part of the current public CE. I used them as a EE customer to plot trajectories and IMU data, nightly benchmark results and the like.

See also my other comment in https://github.com/ternaris/marv-robotics/issues/18#issuecomment-316028033 regarding the state of the CE.

**Comment by chaoflow** [comment]
@mikepurvis @luator We are working on a Community Edition release, which will happen before ROSCon 2017. This release (as well as the Enterprise Edition) will feature support for loading custom widgets. Additionally in EE an integration of the mpld3 library is available, see https://marvhub.com/docs/tutorial/write-your-own.html#combined-table-plot-and-gallery

**Comment by chaoflow** [comment]
CE release 17.11 does not contain an interactive plotting library but instead matplotlib plots are rendered to images:
- https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/detail.py#L107
- https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/gnss.py#L255

It is possible to add custom [frontend widgets](https://ternaris.com/marv-robotics/docs/widgets.html#custom).

Documentation now lives here:
- https://ternaris.com/marv-robotics/docs/
- https://ternaris.com/marv-robotics/docs/tutorial/write-your-own.html#combined-table-plot-and-gallery
