### ISSUE TITLE
Source for JavaScript frontend?

### ISSUE THREAD

**Issue by mikepurvis** [ternaris/marv#14]
Hey, I'm interested in developing some additional visualizations for MARV (#13), but it looks like all of the actual rendering of them (from json) occurs in the JavaScript frontend, which appears to be available only in compiled form:

https://github.com/ternaris/marv/blob/master/marv/app/static/main-built.js

Is there a way to build this myself locally, or somehow extend it?

**Comment by NikolausDemmel** [comment]
AFAIK this is not possible at the moment. I have done some smaller tweaks and fixes on the compiled js, but that quickly gets very tedious.

However, I am much in favor of some sane mechanism to extend the frontend with custom JS code as well, @chaoflow.

**Comment by chaoflow** [comment]
@mikepurvis Support for custom widgets will be part of EE and CE and there will be a CE release before ROSCon 2017. This will enable you to develop additional visualizations. At this point we do not have a timeline for releasing frontend source code.
