### ISSUE TITLE
How to parameterize node calls

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#18]
The nodes have some parameters (resp. "_input_"s) with default-values. What do I need to do in order to change the default parameters of a node from outside, i.e. from within another node's _input_ or from the marv config (e.g. input of section-nodes such as "tilte")?

**Comment by NikolausDemmel** [comment]
I haven't used marv in a while, but IIRC, you can do something like

```
custom_node = existing_node.clone(some_parameter=some_other_value, some_input=some_other_node)
```

Then you reference `custom_node` in the config like any other node.

Not sure if there is a way to set parameters directly from config yet.

**Comment by beetleskin** [comment]
Thanks, that was a good hint and there is definetively this clone function, but it does not work for me:
```python
from marv_robotics.detail import trajectory_section
trajectory_section_quality = trajectory_section.clone(geojson=my_geojson_node, title="My Trajectory")
```
I added `trajectory_section_quality` to the list of nodes and also to the [detail] section in the marv config. The node, resp. its input nodes, are triggered when running all nodes, but no detail section is rendered in the frontend. 
When I copy the original node definition and customize the name and decorators, it works and the detail section is rendered correctly.

**Comment by NikolausDemmel** [comment]
I'm out of ideas then... Can you post the full config file?

@chaoflow?

**Comment by chaoflow** [comment]
@beetleskin what is ``my_geojson_node``? My assumption is that it does not produce any output. Could you paste full minimal working example so we can reproduce the issue you are seeing?

**Comment by chaoflow** [comment]
Correct. Currently, the only way to "change" parameters is by cloning the node.

Cloning persistent nodes is broken, fix scheduled for upcoming release.

**Comment by beetleskin** [comment]
What are "persistent" nodes, and how is it broken?

**Comment by NikolausDemmel** [comment]
> What are "persistent" nodes, not volatile ones?

This part I can answer. Persistent nodes are the ones you list in the config. Their output gets cached. They need to have a pycpnp type (but I guess not all nodes with cpnp type that are run due to some dependency are persistent).
