### ISSUE TITLE
Need for custom message definition

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#19]
Hi, with the "old" marv, I was able to process custom message types as plain python objects without the need for the message definition to be available. 
Now, `get_message_class(stream.msg_type)` obviously returns `None` if the message definition is not available. Do I need to make the definitions available for roslib in order to make the new stream-approach of message processing work?
Background: In our current marv setup (the old version), we're running marv on a server with plain ROS Kinetic only, i.e. without our development catkin workspace. Now it seems that this doesn't fly anymore and I have to compile our workspace and source it additionally to the venv? Or can I, somehow, just work on the messages without the definition being available?

If the definition is not available, how do you serialize the custom messages in the first place?

**Comment by NikolausDemmel** [comment]
I'm not currently using marv (was using it at my previous job). We ran marv in an environment where all message packages were available so we didn't run into this issue.

I believe the previous version of marv was relying on rosbag to deserialize the messages, and then passed around the deserialized message objects.

Now marv reads the raw, serialized messages from rosbag, and passes those around to only deserialize on demand. The current example nodes using `get_message_class(stream.msg_type)` obviously only work if the message package is installed and know to roslib.

However, one could try to mimic the way that rosbag deals with that, using the message definition text that is stored with the rosbag to create temporary message classes for deserialization. IMHO it would be ideal, if marv would support this out of the box, but I guess you could for now add it yourself. I'm not sure how involved the corresponding rosbag code is though.

**Comment by beetleskin** [comment]
That sounds like a good workaround, thanks a lot for the clarification! 
I'll leave this open, though. Maybe there is already support for this somewhere in the API.

**Comment by NikolausDemmel** [comment]
Btw, maybe it is also possible to define your own `messages` node that doesn't pass `raw=True` to `bag.read_messages(...)` (see https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/bag.py#L185-L186) and use it as a replacement for the default `messages` node.

Btw: I believe the reason for this change was that the streams between nodes should be serializable to capnp. The longer term vision is that node computation can be distributed across multiple processes and also machines. That also allows something like implementing nodes in C++. If you have deserialized message objects, you would have to serialize again. I don't know how far these plans have progressed though.

**Comment by beetleskin** [comment]
Ah, I've been wondering about the difference of `mesages` and `raw_messages`, there is none: https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/bag.py#L256 :D 
I guess I could do that right now, but if this contradicts the capnp pipeline, I'd rather make my message definitions available ..
In the past, it was a nice feature that you don't have to install and compile your ros-stack on the Marv server.

**Comment by NikolausDemmel** [comment]
> I guess I could do that right now, but if this contradicts the capnp pipeline, I'd rather make my message definitions available ..

Yes, if you can do it, installing the messsage packages on the server is probably the simplest and quickest short term fix.

> In the past, it was a nice feature that you don't have to install and compile your ros-stack on the Marv server.

I absolutely agree. I would say providing a convenient way to do rosbag style deserialization would be a very natural feature for marv-robotics. It's probably already on their feature list, but no idea with which priority (cc @chaoflow).

**Comment by chaoflow** [comment]
@NikolausDemmel @beetleskin indeed this is on the agenda already. It will not be necessary to have message definitions installed, but instead those stored within the bag file will be used. Meanwhile, did you find a workaround already?

**Comment by chaoflow** [comment]
For completeness, here this is mentioned in the current documentation: https://github.com/ternaris/marv/blob/35c2a72586a755f67b3b223b962845ec63d8b9e8/docs/tutorial/write-your-own.rst#deserialize-raw-message

**Comment by beetleskin** [comment]
Or .. I leave it open until the update is out ..
