### ISSUE TITLE
Best practice for debugging custom nodes

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#20]
While development, I encounter cryptic errors a lot. Is there a best practice to debug custom nodes, started from cli, with the python debugger and step through it? Using ye old debug-prints is very cumbersome and time-consuming.

**Comment by NikolausDemmel** [comment]
Yes, AFAIK ipdb is the way to go. You can set a break out with

```
import pdb; pdb.set_trace()
```

And isn't there a [`marv-ipdb` executable](https://github.com/ternaris/marv-cli/blob/3b6f50fac1b07eedd80ad31c25361a669ae61a85/setup.py#L66) as well that can be used as a drop-in replacement for `marv`.

**Comment by beetleskin** [comment]
That's what I'm was looking for, thanks!
