### ISSUE TITLE
Documentation of the new Trajectory Widget

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#21]
With the old Leaflet-Widget, it was relatively straight forward what features were supported. Since you now use your own proprietary renderer, a documentation is needed:
* JSON object schema
* features
* properties
* types
* styles
* .. anything that is supported by the frontend

The most important thing to tune, for me right now, is the stroke width of the lines since the trajectory is hardly visible on the map. You got "weight" and "markersize" as properties, but they don't seem to have any influence on the rendering.

Also, within the source code, your variables suggest that you use "GeoJSON" but the objects and their structure looks slightly different from the official specs. Some clarifications would be nice here.

Ref: #9

**Comment by NikolausDemmel** [comment]
I agree that documentation is needed.

We have been using the following features:
 - one or multiple trajectories
 - both with and without orientation (displays as a "viewing cone" at the trajectory start)
 - both with playback (timestamps) and without (no timestamps), at least IIRC
 - colors

If you need help with those in particular, I might be able to dig in our latest configuration.

**Comment by beetleskin** [comment]
The playback sounds interesting, how did you manage this?

I found the [capnp types of GeoJson](https://github.com/ternaris/marv/blob/master/marv_nodes/types.capnp#L34), they give a hint on what might be supported by the trajectory renderer in the frontend. I didn't try all the properties yet though.

**Comment by chaoflow** [comment]
@beetleskin The player functionality is EE-only, documentation is planned for the upcoming release. In short:
- we are following https://tools.ietf.org/html/rfc7946
- top-level must be a FeatureCollection
- currently, supported Feature geometries are LineString and Polygon
- weight as a property should work (if it doesn't its a bug which we'd fix with the upcoming release), markersize is only used for the player

**Comment by chaoflow** [comment]
@beetleskin I just verified that adding a ``'weight': 10`` to https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/trajectory.py#L87 leads to a line with more weight.

Note, that you need to also force run ``trajectory_section`` for the newly rendered trajectory to be used. The upcoming release will introduce ``marv run --force-dependent`` to achieve this.

**Comment by beetleskin** [comment]
Thanks. But _weight_ does not work for me in combination with _LineString_. The line is only 1px, no matter to what value _weight_ is set to:

```python
feat = {
            'properties': {
                'color': color,
                'weight': 5.0
            },
            'geometry': {
                'line_string': {
                    'coordinates': feature_coordinates
                }
            }
        }
```

**Comment by beetleskin** [comment]
Got it .. it works in Chromium, but not in FF (57.0.4 (64-bit), Ubuntu 16.04)
