### ISSUE TITLE
Fancy filter widgets

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#24]
On [marvhub](https://marvhub.com/#/collection/bags), you show some graphical filter widgets, reducing the datasets listed. Are they available for the CE, or are they EE only? I didn't find any doc on them.

**Comment by NikolausDemmel** [comment]
IIRC that was an EE-only feature, at least at the time (1/2 year ago).

**Comment by chaoflow** [comment]
Correct, the fancy filter widgets are EE-only. Documentation for the upcoming release will include this.
