### ISSUE TITLE
Possibility to load data from the server

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#26]
Afaik, right now it is not possible to load any additional data from the server from within the `custom.js` sandbox, since you return `301` for all unknonw routes. One could easily fix that by serving all files from within `site/frontend` or `site/custom_data` or whatever.

My usecase is to load more javascript libraries or CSS files.

**Comment by NikolausDemmel** [comment]
Maybe you can [serve static files with uwsgi](http://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html)? I thought the was a way when running plain marv as well, but I might remember wrongly @chaoflow?

**Comment by beetleskin** [comment]
UWSGI config could work, thanks!
