### ISSUE TITLE
About HTTPS

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#27]
I'm trying to [deploy](https://github.com/ternaris/marv/blob/7f88dc91b5f4117d637c76c5969367c7bb729a96/docs/deploy.rst) my marv app, but stumble upon the need for HTTPS. When using the dev-config for wsgi and accessing marv not via localhost but with the url of the machine, I get:
```
Your MARV installation is not secured. Please make sure your webserver serves MARV over an encrypted https connection.
```

So somewhere hidden, you enforce the need for HTTPS. However, our marv runs only in the intranet and is encapsulated with docker. Hence, there is no strong need for HTTPS and I'd like to avoid the setup-overhead for this. 

However, I was not able to find any hints on how to circumvent this issue, any ideas?

---

Btw, one has to build uwsgi from source, and install _libssl-dev_ beforehand in order to use it with https:
```
sudo apt-get install libssl-dev
pip install --upgrade --force-reinstall https://projects.unbit.it/downloads/uwsgi-lts.tar.gz
```

**Comment by stsundermann** [comment]
This project contains a deobfuscated angularjs(?) application. Luckily there are some tools you can use to deobfuscate the code. You can deobfuscate main-built.js using Chrome's developer tools pretty print feature. You need to patch the variable "insecure" which should be around line 1270. Just change the check to always return false. Then just serve your deobfuscated file instead of the bundled one.

**Comment by stsundermann** [comment]
I pushed a version in my fork which has no https check @ https://github.com/stsundermann/marv

**Comment by chaoflow** [comment]
@beetleskin Thank you for pointing out how to get uwsgi with https support. Documentation in next release is updated accordingly.

Marv requires https (except on localhost) for service workers to be available. The service worker is not in use, yet, but we'll start making use of it later this year.

As a side note: We consider it a bad idea to treat networks as trusted and recommend to use https also in intranets.
