### ISSUE TITLE
IndexError: deque index out of range

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#28]
Hi, I got another error when processing custom nodes:

```bash
2018-01-10 18:47:27,737 ERRO marv.run Failed to get MsgRequest(<Handle gyaodp4dtx.my_node.ccenyjnv4q.default>, 0) for <Driver gyaodp4dtx.my_other_node.rxyxtmlagk.default>
2018-01-10 18:40:41,893 ERRO marv.cli Exception occured for dataset rjij5fk4pmslgqtcaon6mvh6va:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marv/cli.py", line 390, in marvcli_run
    cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv/site.py", line 355, in run
    deps=deps, cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 75, in run_nodes
    done, send_queue_empty = process_task(current, task)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 356, in process_task
    send = stream.get_msg(req) if stream is not None else None
  File "/usr/local/lib/python2.7/dist-packages/marv_store/streams.py", line 144, in get_msg
    msg = self.cache[offset]
IndexError: deque index out of range
```

It is not triggered for every bag, only for some, but I couldn't get my head around it. `offset` is something bigger than `len(self.cache)` .. how can that happen? The node triggering this guy takes two input streams, one is a ROS message stream, one a custom capnp type stream (the node generating this one is then has a ROS msg input). Both have more than one message but the total number of objects in each stream differs from bag to bag. I pull both streams sequentially after one another.

The error is not triggered, when I run custom capnp input node beforehand explicitly. So it seems to be an issue of triggering the input stream node?

**Comment by NikolausDemmel** [comment]
@chaoflow, this looks like the issue we also had when pulling multiple streams. We'd need "pull_any" or something of the like, no?

**Comment by beetleskin** [comment]
Sounds legit. However, how can I use `pull_all` if the streams differ in total number of messages? That's rather cumbersome, wehen you need both streams to be complete:

```
@marv.node(GeoJson)
@marv.input('foo_stream', default=marv.select(raw_messages, "/foo"))
@marv.input('bar_stream', default=bar)
def foobar_geojson(foo_stream, bar_stream):
    log = yield marv.get_logger()
    yield marv.set_header(title="foobar_geojson")

    foos = []
    bars = []

    # unpack streams
    pytype = get_message_class(foo_stream.msg_type)
    rosmsg = pytype()
    
    while True:
        foo, bar = yield marv.pull_all(foo_stream, bar_stream)
        if foo is None and bar is None:
            break
        if foo is not None:
            foos.append(foo)
        if bar is not None:
            bars.append(bar)

    # do something with foo and bar
```

vs

```
@marv.node(GeoJson)
@marv.input('foo_stream', default=marv.select(raw_messages, "/foo"))
@marv.input('bar_stream', default=bar)
def foobar_geojson(foo_stream, bar_stream):
    log = yield marv.get_logger()
    yield marv.set_header(title="foobar_geojson")

    foos = []
    bars = []

    # unpack streams
    pytype = get_message_class(foo_stream.msg_type)
    rosmsg = pytype()
    
    while True:
        foo = yield marv.pull(foo_stream)
        if foo is None:
            break
        foos.append(foo)

    while True:
        bar = yield marv.pull(bar_stream)
        if bar is None:
            break
        bars.append(bar)

    # do something with foo and bar
```

**Comment by chaoflow** [comment]
@beetleskin First, the error message reveals internals that are not useful for somebody writing a node. We'll improve on that. Messages for selected topics are read into streams. Streams are cached in memory in deques and the error message means that a node tried to access a message that is not cached anymore. While the cache size can be increase, see ``marv run --help``, it usually means that the node graph should be restructured.

In your first example you pull them synchronously. Your node will be activated again once both are available, if one is very frequent, but the other isn't, you should see the error message you are seeing.

In the second example you first pull all foos and then all bars, but the first bar is probably gone from the deque before all foos are read.

If you want to read all foos and all bars and only then process them, you will need to hold them in memory within your nodes. The solution is one volatile node, ``@marv.node()`` without type, that consume all foos into a list and only then pushes that list as a single message, and another that does the same for bars.

Your foobar_geojson then consumes the streams produced by these accumulators, receiving one message from each.

**Comment by chaoflow** [comment]
@beetleskin could you describe what exactly you would expect from marv?

**Comment by chaoflow** [comment]
@beetleskin Your full node graph would be helpful to give proper advice and decide whether we miss something.

**Comment by beetleskin** [comment]
I'd expect that I don't have to pay attention to the nature of the incoming streams, i.e. how many messages they include or if the streams are in sync and have the same message count. Because this differs from bag to bag, topic to topic and input stream to input stream. 
I'd expect that I can just pull the streams until they're finished, no matter what lies behind them (ros-message, python, capnp, cutom node, marv node, ..).Also, it is hard to comprehend which of the input streams is the trouble maker.

I ended up with your suggestion to wrap one input stream (my custom node output) into a List. Now it works. But doesn't this violate the whole streaming idea?

**Comment by chaoflow** [comment]
This was caused when a node tried to pull messages that were not available anymore. A proper error message is printed now, pointing to https://ternaris.com/marv-robotics/docs/patterns.html#reduce-separately

**Comment by chaoflow** [comment]
@beetleskin Efficient streaming necessitates a node graph that processes messages when they are published. The issue reported here arises for example if one node requests two streams but only processes many messages (more than 50) of one stream before attending to the next one. if marv would keep all messages until they are pulled by all nodes that subscribed the streams, we would encourage people to create badly designed node graphs.

If you have a use case where [reducing separately](https://ternaris.com/marv-robotics/docs/patterns.html#reduce-separately) does not work or where you see how marv could help in more efficient processing, please open a new issue in https://github.com/ternaris/marv-robotics/issues.

Thank you very much for your feedback!
