### ISSUE TITLE
AssertionError: assert not any(driver for lst in waiting.values()

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#29]
Yet another one:

```
2018-01-10 18:45:52,911 ERRO marv.cli Exception occured for dataset uz5mmlgptdvtwuuhp7kmmin3fy:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marv/cli.py", line 390, in marvcli_run
    cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv/site.py", line 355, in run
    deps=deps, cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 76, in run_nodes
    after()
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 426, in after_loop
    assert not any(driver for lst in waiting.values()
AssertionError
```

**Comment by chaoflow** [comment]
@beetleskin you surely do find plenty of ways to use marv, we haven't so far... Thanks for all the reports! Could you post a minimal working example for this as well? It greatly simplifies debugging.

**Comment by chaoflow** [comment]
Meanwhile, we'd get plenty of information if you run marv with the following parameters:
```
$ PPINFO=1 marv -vvv run ...
```

**Comment by beetleskin** [comment]
The error occurs for a node that pulls a ros topic of custom type. In some bags, this topic does not exist.It pushes a Section with a table widget:
```
@marv.node(Section)
@marv.input('title', default='User Annotations')
@marv.input('stream', marv.select(raw_messages, "/user_annotation"))
def annotations_section(title, stream):
  .. create a fancy table
```

What happens with `marv.select(raw_messages, "/user_annotation")` iff there is no such topic?

**Comment by chaoflow** [comment]
@beetleskin ``marv.select(raw_messages, "/user_annotation")`` requests a stream of the raw_message node that mathes the topic named ``/user_annotation``. When directly used, the instantiated node waits for this stream to appear, which never happens. See #25 for a workaround using ``foreach``. However, a section cannot use foreach. As a workaround you need an intermediate node that uses foreach and the section to be modeled after the other sections in ``marv_robotics/detail.py`` and also the example in #25.

Regarding your update 3, ``marv.select`` is correct, the comment refers to the code within ``marv.select``, which you should not use directly. See also https://github.com/ternaris/marv-robotics/issues/25#issuecomment-362814838

**Comment by chaoflow** [comment]
We'll treat this issue to be about the uninformative assertion. Let's continue on #25 for support for optional inputs.

**Comment by beetleskin** [comment]
#25 is something completely different, which issue are you referring to?

**Comment by chaoflow** [comment]
@beetleskin thx! it's 25 in marv-robotics https://github.com/ternaris/marv-robotics/issues/25. Just updated the comments above.
