### ISSUE TITLE
trajectory weight is ignored in Firefox

### ISSUE THREAD

**Issue by chaoflow** [ternaris/marv#31]
from #21 

works in:
- Chrome

fails in:
- Firefox (57.0.4 (64-bit), Ubuntu 16.04)

**Comment by beetleskin** [comment]
strange .. I just tested with a colleague's computer. At his machine it failed for both, FF and Chromium (Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) while it works on my Chromium (same version, same system, different desktop env though).
