### ISSUE TITLE
No such command "group"

### ISSUE THREAD

**Issue by sebastianscherer** [ternaris/marv#35]
When follwoing the instructions of the [Tutorial: Setup basic site](https://ternaris.com/marv-robotics/docs/tutorial/setup-basic-site.html), the steps in section "Create user account" do not work:

```
$ marv group adduser testuser admin
Usage: marv [OPTIONS] COMMAND [ARGS]...

Error: No such command "group".
```

Could this be due to the tutorial be outdated? The html header says it is for MARV 2.0.0b9

**Comment by chaoflow** [comment]
@sebastianscherer thank you for reporting. Group management is currently EE only, in CE all users have the same permissions. There is no need to add the user to an admin group. We'll fix the tutorial accordingly.
