### ISSUE TITLE
Error: no such option: --all-datasets

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#36]
Running `marv run --all-datasets` yields `Error: no such option: --all-datasets`. However, the `--help` suggests such an option.

**Comment by chaoflow** [comment]
@beetleskin that has become ``marv run --collection=*`` for all collections or more specific with individual collections.

**Comment by beetleskin** [comment]
I know, still the help is misleading.

**Comment by chaoflow** [comment]
@beetleskin Yes, fix is scheduled for next release - sorry for not being clear about that before. Thx for reporting!
