### ISSUE TITLE
basic form of acl to require login also for read access

### ISSUE THREAD

**Issue by chaoflow** [ternaris/marv#37]
In its present state, unauthenticated users may read and authenticated users may comment and delete datasets. There will be at least a basic configuration option to influence that.

As workaround replace occurrences of ``__unauthenticated__`` with ``__authenticated__`` in ``marv_webapi/dataset.py`` and ``marv_webapi/collection.py``.

https://github.com/ternaris/marv/search?utf8=%E2%9C%93&q=__unauthenticated__&type=

from #15 https://github.com/ternaris/marv-robotics/issues/23

**Comment by Earthwings** [comment]
I'm using that workaround, and a quite similar one to influence who is able to delete/comment/tag:
`sed -i 's/__authenticated__/__admin__/g' marv_webapi/{delete,comment,tag}.py`
Config options for each will be a very welcome addition, thanks!

**Comment by bst** [comment]
Is there any progress on this? Configuration options would be really helpful for as, as well.

**Comment by chaoflow** [comment]
@sebastianscherer yes, this will be include in the upcoming release.
