### ISSUE TITLE
install_requires incomplete

### ISSUE THREAD

**Issue by sebastianscherer** [ternaris/marv#39]
Hi,

this is related to #16 but our real problem was not solved yet: Yes, we can install marv after pip-sync, but we do not want that. Would it not be good practice to keep both [install_requires and requirements](https://packaging.python.org/discussions/install-requires-vs-requirements/) up to date so the package also installs without pip-sync in a clean virtual environment?

You do seem to have used [install_requires](https://github.com/ternaris/marv/blob/7a000dedfff2daa74f44cda213e8e1c20b2a0316/setup.py#L68) at some point in time (otherwise: Why not leave it empty?). Could you update it again? It is currently missing at least the entry for cython, maybe more.

Thanks,
Sebastian

**Comment by chaoflow** [comment]
@sebastianscherer pycapnp did not declare the dependencies. This is fixed for pycapnp-for-marv for the upcoming release. Thank you for pointing this out.
