### ISSUE TITLE
marvhub: Creating user with github / google login seems flaky

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv#45]
After logging in you are asked to set a nickname, but you cannot continue from there. See also: 
https://discourse.ros.org/t/rosbag-sharing-place/1956/26?u=nikolausdemmel

**Comment by chaoflow** [comment]
@NikolausDemmel thx for reporting. Fixed as part of 18.04 deployment.

**Comment by NikolausDemmel** [comment]
Cool, thanks. It worked for me with github, but somehow I had to try 2x. The first time I got to "set nickname" and pressed enter, that left me logged out. The second time I got to "set nickname" and clicked on the button, which created the account and left me logged in. You might want to check if "Enter" in that dialog does the right thing.

**Comment by chaoflow** [comment]
Thx! Let's keep an eye on this.
