### ISSUE TITLE
Add support for multiple trajectory layers

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#7]
Right now, the osm-widget only suports one trajectory, resp. one leaflet-layer. We want to visualize more data by writing our own _geo_json_trajectory_-nodes and forward them to the widget. The code responsible for setting the trajectory seems to be [baked](https://github.com/ternaris/marv/blob/master/marv/app/static/main-built.js#L769) with bower, so I can't really offer you a pull-request. But I propose to use a _name_ property within each feature property dict to display and toggle the individual trajectories:

```javascript
{
  'type': 'FeatureCollection', 
  'features': {
    'type': 'Feature',
    'properties': {
      'name' : "trajectory_1"
    },
    'geometry': {...}
  },  {
    'type': 'Feature',
    'properties': {
      'name' : "trajectory_2"
    },
    'geometry': {...}
  }
}
```

**Comment by chaoflow** [comment]
@beetleskin the new trajectory widget gives you full control of this, see: https://github.com/ternaris/marv-robotics/blob/34c18d90ce150a96a3d82219f47c7f0630634039/marv_robotics/detail.py#L175.
