### ISSUE TITLE
BUG: marker image broken for point geometry

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#8]
I played with your geo_json_trajectory-node and replaced linestrip with plain points. Usually within leaflet they are rendered as pins. However, the image is missing. The HTML-node has the src property `src="/bower_components/leaflet/dist/imagesmarker-icon.png"`, but it needs to be `src="/bower_components/leaflet/dist/images/marker-icon.png"`.

**Comment by beetleskin** [comment]
I just found out that this is not your fault: https://github.com/Leaflet/Leaflet/issues/4968. I guess you can close this as soon as this is fixed upstream and merged into your app.

**Comment by NikolausDemmel** [comment]
Linked from that issue, this seems to be the currently suggested workaround: https://github.com/PaulLeCam/react-leaflet/issues/255#issuecomment-261904061

**Comment by chaoflow** [comment]
Closing as this issue is about leaflet which marv is not using anymore.
