### ISSUE TITLE
Add support for custom leaflet popups and tooltips

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#9]
From the python-side, there is no way of defining popups for points in a leaflet map, since leaflet does not define any default properties it reads. Can you add such default properties, i.e. listen for `properties.popup_content` and `properties.tooltip`?

http://leafletjs.com/examples/geojson/

**Comment by NikolausDemmel** [comment]
Yeah, support for getting text into leaflet would be great. Tooltips, popups, some kind of direct text-overlay, ...

**Comment by chaoflow** [comment]
We replaced the leaflet library with a slim opengl-based implementation. If you are missing features in that new [trajectory widget](https://ternaris.com/marv-robotics/docs/widgets.html#trajectory) please open feature requests.

To continue using leafletjs, it can be added as a [custom widget](https://ternaris.com/marv-robotics/docs/widgets.html#custom) including plugins of your choice.
